[package]
name = "tracer"
version = "0.1.0"
authors = ["Emil Imbert Villumsen <emimvi@gmail.com>"]

[dependencies]
rand = "0.4"
rayon = "1.0.1"
tobj = "0.1.6"
image = "*"
bvh = { git = "https://github.com/emimvi/tracer_bvh" }
clap = "~2.32"
lazy_static = "1.2.0"
minifb = "0.12"
