[package]
name = "openglwindow"
version = "0.1.0"
authors = ["Emil Imbert Villumsen <emimvi@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.6.0"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
